### ISSUE TITLE
Lots of unecessary/confusing variables

### ISSUE THREAD

**Issue by aakilfernandes** [GuildCrypt/oathforge#5]
There's lots of places where variable names are either misleading, or variables are created which are never used/tested.

An example:
https://github.com/GuildCrypt/oathforge/blob/quillhash-audit/test/web3/oathForge.js#L208
`newowner1` here is not an owner. Also, there is nothing done with the variable

**Comment by abhisharma1357** [comment]
Variable names are used that are easily understood with comments, you can find in my repo
