### ISSUE TITLE
Web3-test tests for 0 tokens minted, even though token minted in previous line

### ISSUE THREAD

**Issue by aakilfernandes** [GuildCrypt/oathforge#7]
https://github.com/GuildCrypt/oathforge/blob/web3-tests/test/web3/oathForge.js#L125-L129

Test says 'Next token id without any minting should be 0' however, in a previous line a token is minted

https://github.com/GuildCrypt/oathforge/blob/web3-tests/test/web3/oathForge.js#L119

**Comment by mortimr** [comment]
@aakilfernandes Tests are independent, this means actions done in some tests will never impact other tests. Minting a token in a test, will not result in having a minted token in all the following tests. 

This is done with the `revert` and `snapshot` rpc methods exposed by ganache. I revert the state of the test blockchain to an initial state (where the contract has been freshly deployed) before every single test.

So there is no issue with this test, it tests what the description actually says.

**Comment by aakilfernandes** [comment]
Got it, will close
